image: python:3.9-slim-buster  # Image Docker pour l'environnement CI

stages:
  - build  # Étape de build (packaging)
  - deploy # Étape de déploiement (simplifiée pour l'exemple)

<<<<<<< HEAD
build_client:  # Job pour l'étape de build du client
  stage: build
  script:
    - echo "Packaging Seahawks Harvester Client..."
    - pip install -r requirements.txt  # Installer les dépendances (si tu as un requirements.txt)
    - apt-get update && apt-get install -y zip  # Installer zip pour créer l'archive
    - zip -r seahawks_harvester_client.zip . -x "*.git*" "*.log*"  # Créer une archive zip de tout le dossier, excluant .git et les logs
    - echo "Client packagé dans seahawks_harvester_client.zip"
  artifacts:
    paths:
      - seahawks_harvester_client.zip  # Sauvegarder l'archive comme artifact du job
    expire_in: 1 week # Les artifacts expirent après 1 semaine

deploy_client:  # Job pour l'étape de déploiement (SIMPLIFIÉ - à adapter)
  stage: deploy
  script:
    - echo "Déploiement simplifié du client (copie de l'archive)..."
    - mkdir -p /deployments/client  # Créer un dossier de déploiement (exemple)
    - cp seahawks_harvester_client.zip /deployments/client/  # Copier l'archive dans le dossier de déploiement
    - echo "Archive du client copiée dans /deployments/client/"
  artifacts:
    paths:
      - /deployments/client/seahawks_harvester_client.zip # Sauvegarder l'artifact "déployé" (pour vérification)
    expire_in: 1 week
  dependencies: # Dépend de l'étape de build (attend que build_client termine)
    - build_client
=======
build_client:  
  stage: build
  script:
    - echo "Packaging Seahawks Harvester Client..."
    - pip install -r requirements.txt 
    - apt-get update && apt-get install -y zip  
    - zip -r seahawks_harvester_client.zip . -x "*.git*" "*.log*"  
    - echo "Client packagé dans seahawks_harvester_client.zip"
  artifacts:
    paths:
      - seahawks_harvester_client.zip  
    expire_in: 1 week 

deploy_client:  
  stage: deploy
  script:
    - echo "Déploiement simplifié du client (copie de l'archive)..."
    - mkdir -p /deployments/client  
    - cp seahawks_harvester_client.zip /deployments/client/  
    - echo "Archive du client copiée dans /deployments/client/"
  artifacts:
    paths:
      - /deployments/client/seahawks_harvester_client.zip 
    expire_in: 1 week
  dependencies: 
    - build_client
>>>>>>> 79cbb202fee30e21754941112a810ffdd095f997
