image: python:3.9-slim-buster  # Image Docker pour l'environnement CI

stages:
  - build  # Étape de build (packaging)
  - deploy # Étape de déploiement (simplifiée pour l'exemple)

build_client:  
  stage: build
  script:
    - echo "Packaging Seahawks Harvester Client..."
    - pip install -r requirements.txt 
    - apt-get update && apt-get install -y zip  
    - zip -r seahawks_harvester_client.zip . -x "*.git*" "*.log*"  
    - echo "Client packagé dans seahawks_harvester_client.zip"
  artifacts:
    paths:
      - seahawks_harvester_client.zip  
    expire_in: 1 week 

deploy_client:  
  stage: deploy
  script:
    - echo "Déploiement simplifié du client (copie de l'archive)..."
    - mkdir -p /deployments/client  
    - cp seahawks_harvester_client.zip /deployments/client/  
    - echo "Archive du client copiée dans /deployments/client/"
  artifacts:
    paths:
      - /deployments/client/seahawks_harvester_client.zip 
    expire_in: 1 week
  dependencies: 
    - build_client
